package com.fitness.domain.model.edamam

data class TotalNutrients(
    val ca: NutrientsMetaData? = null,
    val chocdf: NutrientsMetaData? = null,
    val chocdfnet: NutrientsMetaData? = null,
    val chole: NutrientsMetaData? = null,
    val enerckcal: NutrientsMetaData? = null,
    val fams: NutrientsMetaData? = null,
    val fapu: NutrientsMetaData? = null,
    val fasat: NutrientsMetaData? = null,
    val fat: NutrientsMetaData? = null,
    val fatrn: NutrientsMetaData? = null,
    val fe: NutrientsMetaData? = null,
    val fibtg: NutrientsMetaData? = null,
    val folac: NutrientsMetaData? = null,
    val foldfe: NutrientsMetaData? = null,
    val folfd: NutrientsMetaData? = null,
    val k: NutrientsMetaData? = null,
    val mg: NutrientsMetaData? = null,
    val na: NutrientsMetaData? = null,
    val nia: NutrientsMetaData? = null,
    val p: NutrientsMetaData? = null,
    val procnt: NutrientsMetaData? = null,
    val ribf: NutrientsMetaData? = null,
    val sugar: NutrientsMetaData? = null,
    val sugaradded: NutrientsMetaData? = null,
    val thia: NutrientsMetaData? = null,
    val tocpaha: NutrientsMetaData? = null,
    val vitarAE: NutrientsMetaData? = null,
    val vitb12: NutrientsMetaData? = null,
    val vitb6a: NutrientsMetaData? = null,
    val vitc: NutrientsMetaData? = null,
    val vitd: NutrientsMetaData? = null,
    val vitk1: NutrientsMetaData? = null,
    val water: NutrientsMetaData? = null,
    val zn: NutrientsMetaData? = null,
)